# Generated by Django 5.2.14 on 2026-05-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secondcareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_describtion', models.TextField()),
                ('job_image', models.ImageField(upload_to='secondcareer')),
            ],
        ),
    ]
