# Generated by Django 5.2.14 on 2026-05-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondcareer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondcareer',
            old_name='job_describtion',
            new_name='job_description',
        ),
    ]
